################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
ARCHIVES := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Debug-WIN/couriercxx/connection \
Debug-WIN/couriercxx/connection/event \
Debug-WIN/couriercxx/connector \
Debug-WIN/couriercxx/connector/bluetooth \
Debug-WIN/couriercxx/connector/gpio \
Debug-WIN/couriercxx/connector/i2c \
Debug-WIN/couriercxx/connector/scsi \
Debug-WIN/couriercxx/connector/serialport \
Debug-WIN/couriercxx/connector/spi \
Debug-WIN/couriercxx/connector/udp \
Debug-WIN/couriercxx/db \
Debug-WIN/couriercxx/device \
Debug-WIN/couriercxx/device/bluetooth \
Debug-WIN/couriercxx/event \
Debug-WIN/couriercxx/event/event \
Debug-WIN/couriercxx/image \
Debug-WIN/couriercxx/logger \
Debug-WIN/couriercxx/network \
Debug-WIN/couriercxx/network/http \
Debug-WIN/couriercxx/network/tcp \
Debug-WIN/couriercxx/network/udp \
Debug-WIN/couriercxx/property \
Debug-WIN/couriercxx/sound \
Debug-WIN/couriercxx/util \
Release-WIN/couriercxx/connection \
Release-WIN/couriercxx/connection/event \
Release-WIN/couriercxx/connector \
Release-WIN/couriercxx/connector/bluetooth \
Release-WIN/couriercxx/connector/gpio \
Release-WIN/couriercxx/connector/i2c \
Release-WIN/couriercxx/connector/scsi \
Release-WIN/couriercxx/connector/serialport \
Release-WIN/couriercxx/connector/spi \
Release-WIN/couriercxx/connector/udp \
Release-WIN/couriercxx/db \
Release-WIN/couriercxx/device \
Release-WIN/couriercxx/device/bluetooth \
Release-WIN/couriercxx/event \
Release-WIN/couriercxx/event/event \
Release-WIN/couriercxx/image \
Release-WIN/couriercxx/logger \
Release-WIN/couriercxx/network \
Release-WIN/couriercxx/network/http \
Release-WIN/couriercxx/network/tcp \
Release-WIN/couriercxx/network/udp \
Release-WIN/couriercxx/property \
Release-WIN/couriercxx/sound \
Release-WIN/couriercxx/util \
couriercxx/connection \
couriercxx/connection/event \
couriercxx/connector \
couriercxx/connector/bluetooth \
couriercxx/connector/gpio \
couriercxx/connector/i2c \
couriercxx/connector/scsi \
couriercxx/connector/serialport \
couriercxx/connector/spi \
couriercxx/connector/udp \
couriercxx/db \
couriercxx/device \
couriercxx/device/bluetooth \
couriercxx/event \
couriercxx/event/event \
couriercxx/image \
couriercxx/logger \
couriercxx/network \
couriercxx/network/http \
couriercxx/network/tcp \
couriercxx/network/udp \
couriercxx/property \
couriercxx/sound \
couriercxx/util \

