DIR=couriercxx
LIB_NAME=libCourierCXX.a

install: uninstall
	sudo mkdir -p /usr/local/include/$(DIR)
	sudo find ../$(DIR) -name "*.h" -type f -exec cp --parents \{\} /usr/local/include/$(DIR) \;
	sudo cp $(LIB_NAME) /usr/local/lib

uninstall:
	sudo rm -rf /usr/local/include/$(DIR)
	sudo rm -f /usr/local/lib/$(LIB_NAME)
	
examples:	
	cd ../examples && ./make

utils:
	cd ../utils && ./make
	
docs:
	cd ../ && doxygen config.doxygen
	
