#!/bin/sh

g++ -o LoopPortTest LoopPortTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o NonBlockSerialPortTest NonBlockSerialPortTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o ClockTest ClockTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o SerialPortTimeoutTest SerialPortTimeoutTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o BMPTest BMPTest.cpp -std=c++14 -lCourierCXX -lpthread 
g++ -o JPGTest JPGTest.cpp -std=c++14 -lCourierCXX -lpthread -ljpeg
g++ -o UDPServerTest UDPServerTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o UDPClientTest UDPClientTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o HTTPClientTest HTTPClientTest.cpp -std=c++14 -lCourierCXX -lpthread -levent
