#!/bin/sh

g++ -std=c++17 -o BMPTest                BMPTest.cpp                -lCourierCXX -lpthread
g++ -std=c++17 -o ClockTest              ClockTest.cpp              -lCourierCXX -lpthread
g++ -std=c++17 -o HTTPClientTest         HTTPClientTest.cpp         -lCourierCXX -lpthread -levent
g++ -std=c++17 -o JPGTest                JPGTest.cpp                -lCourierCXX -lpthread -ljpeg
g++ -std=c++17 -o LoopPortTest           LoopPortTest.cpp           -lCourierCXX -lpthread
g++ -std=c++17 -o NonBlockSerialPortTest NonBlockSerialPortTest.cpp -lCourierCXX -lpthread
g++ -std=c++17 -o SerialPortTimeoutTest  SerialPortTimeoutTest.cpp  -lCourierCXX -lpthread
g++ -std=c++17 -o UDPClientTest          UDPClientTest.cpp          -lCourierCXX -lpthread 
g++ -std=c++17 -o UDPServerTest          UDPServerTest.cpp          -lCourierCXX -lpthread
