#!/bin/sh

g++ -o LoopPortTest LoopPortTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o NonBlockSerialPortTest NonBlockSerialPortTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o ClockTest ClockTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o SerialPortTimeoutTest SerialPortTimeoutTest.cpp -std=c++14 -lCourierCXX -lpthread
g++ -o BMPTest BMPTest.cpp -std=c++14 -lCourierCXX -lpthread 
