#!/bin/sh

g++ -std=c++17 -o BluetoothPortExample         BluetoothPortExample.cpp         -lCourierCXX -lpthread -lbluetooth -fpermissive
g++ -std=c++14 -o ConfigurationDatabaseExample ConfigurationDatabaseExample.cpp -lCourierCXX -lpthread -lpqxx
g++ -std=c++17 -o GPIOPortExample              GPIOPortExample.cpp              -lCourierCXX -lpthread
g++ -std=c++17 -o I2CPortExample               I2CPortExample.cpp               -lCourierCXX -lpthread
g++ -std=c++17 -o NetExample                   NetExample.cpp                   -lCourierCXX -lpthread
g++ -std=c++17 -o PWMExample                   PWMExample.cpp                   -lCourierCXX -lpthread
g++ -std=c++17 -o SerialPortExample            SerialPortExample.cpp            -lCourierCXX -lpthread
g++ -std=c++17 -o ServerExample                ServerExample.cpp                -lCourierCXX -lpthread -levent
g++ -std=c++17 -o SnifferExample               SnifferExample.cpp               -lCourierCXX -lpthread -lpcap
